export const SortBy = [
    { name: "id", key: "id" },
    { name: "name", key: "name.raw" },
    { name: "isCorporate", key: "isCorporate" },
    { name: "channelId", key: "channelId" },
    { name: "language", key: "language" },
    { name: "zoneId", key: "zoneId" },
    { name: "startDate", key: "startDate" },
    { name: "endDate", key: "endDate" },
    { name: "url", key: "url.raw" },
    { name: "active", key: "active" },
    { name: "priority", key: "priority" },
    { name: "fileId", key: "fileId" },
    { name: "createdAt", key: "createdAt" },
    { name: "createdBy", key: "createdBy" },
    { name: "modifiedAt", key: "modifiedAt" },
    { name: "modifiedBy", key: "modifiedBy" },
    { name: "labels", key: "labels" },
]
