stages:
  - build

variables:
  NODE_VERSION: "14"  # Choose the desired Node.js version

before_script:
  - apt-get update -qy && apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
  - apt-get install -y nodejs
  - npm install -g @angular/cli

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - ng lint
    - ng build --configuration=production
