export const SortBy = [
    { name: "id", key: "id" },
    { name: "name", key: "name.raw" },
    { name: "Corporate", key: "isCorporate" },
    { name: "channel Id", key: "channelId" },
    { name: "language", key: "language" },
    { name: "zone Id", key: "zoneId" },
    { name: "start Date", key: "startDate" },
    { name: "end Date", key: "endDate" },
    { name: "url", key: "url.raw" },
    { name: "active", key: "active" },
    { name: "priority", key: "priority" },
    { name: "file Id", key: "fileId" },
    { name: "created Date", key: "createdAt" },
    { name: "created By", key: "createdBy" },
    { name: "modified Date", key: "modifiedAt" },
    { name: "modified By", key: "modifiedBy" },
]
